# Generated by Django 6.0.7 on 2026-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
